name: Build&Dockerize
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      run: dotnet publish --configuration Release --no-restore -o publish
    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name == 'push' }}
      with:
        name: published-${{ matrix.os }}
        path: publish
