name: Build&Dockerize
on:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        dotnet-quality: 'preview'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publich
      run: dotnet publish --configuration Release --no-restore -o publish
    - uses: actions/upload-artifact@v3
      with:
        name: published
        path: publish
